apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: "airflow"
    name: "airflow"
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "airflow:latest"
    resources: {}
    source:
      git:
        ref: master
        uri: https://github.com/atgreen/ocp-airflow.git
      contextDir:
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
        from:
          kind: ImageStreamTag
          name: python:latest
          namespace: openshift
        forcePull: true
      type: Docker
kind: List
metadata: {}
